package com.example.rdsreadonlytest.application.mapper;

import com.example.rdsreadonlytest.domain.model.Account;
import com.example.rdsreadonlytest.domain.model.AccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    long countByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int deleteByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int insert(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int insertSelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    List<Account> selectByExampleWithRowbounds(AccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    List<Account> selectByExample(AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    Account selectByPrimaryKey(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Account row, @Param("example") AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Account row);
}