package com.example.rdsreadonlytest.domain.model;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Database Table Remarks:
 *   ユーザアカウント
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms.account
 */
public class Account implements Serializable {
    /**
     * Database Column Remarks:
     *   ユーザ名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.created_date
     *
     * @mbg.generated
     */
    private LocalDateTime createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_modified_by
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_modified_date
     *
     * @mbg.generated
     */
    private LocalDateTime lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.allowed_ip
     *
     * @mbg.generated
     */
    private String allowedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.api_key
     *
     * @mbg.generated
     */
    private String apiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.image_uuid
     *
     * @mbg.generated
     */
    private String imageUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.profile
     *
     * @mbg.generated
     */
    private String profile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.username
     *
     * @return the value of cms.account.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.username
     *
     * @param username the value for cms.account.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.version
     *
     * @return the value of cms.account.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.version
     *
     * @param version the value for cms.account.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.created_by
     *
     * @return the value of cms.account.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.created_by
     *
     * @param createdBy the value for cms.account.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.created_date
     *
     * @return the value of cms.account.created_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.created_date
     *
     * @param createdDate the value for cms.account.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.last_modified_by
     *
     * @return the value of cms.account.last_modified_by
     *
     * @mbg.generated
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.last_modified_by
     *
     * @param lastModifiedBy the value for cms.account.last_modified_by
     *
     * @mbg.generated
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.last_modified_date
     *
     * @return the value of cms.account.last_modified_date
     *
     * @mbg.generated
     */
    public LocalDateTime getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.last_modified_date
     *
     * @param lastModifiedDate the value for cms.account.last_modified_date
     *
     * @mbg.generated
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.allowed_ip
     *
     * @return the value of cms.account.allowed_ip
     *
     * @mbg.generated
     */
    public String getAllowedIp() {
        return allowedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.allowed_ip
     *
     * @param allowedIp the value for cms.account.allowed_ip
     *
     * @mbg.generated
     */
    public void setAllowedIp(String allowedIp) {
        this.allowedIp = allowedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.api_key
     *
     * @return the value of cms.account.api_key
     *
     * @mbg.generated
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.api_key
     *
     * @param apiKey the value for cms.account.api_key
     *
     * @mbg.generated
     */
    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.department
     *
     * @return the value of cms.account.department
     *
     * @mbg.generated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.department
     *
     * @param department the value for cms.account.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.email
     *
     * @return the value of cms.account.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.email
     *
     * @param email the value for cms.account.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.first_name
     *
     * @return the value of cms.account.first_name
     *
     * @mbg.generated
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.first_name
     *
     * @param firstName the value for cms.account.first_name
     *
     * @mbg.generated
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.image_uuid
     *
     * @return the value of cms.account.image_uuid
     *
     * @mbg.generated
     */
    public String getImageUuid() {
        return imageUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.image_uuid
     *
     * @param imageUuid the value for cms.account.image_uuid
     *
     * @mbg.generated
     */
    public void setImageUuid(String imageUuid) {
        this.imageUuid = imageUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.last_name
     *
     * @return the value of cms.account.last_name
     *
     * @mbg.generated
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.last_name
     *
     * @param lastName the value for cms.account.last_name
     *
     * @mbg.generated
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.password
     *
     * @return the value of cms.account.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.password
     *
     * @param password the value for cms.account.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.profile
     *
     * @return the value of cms.account.profile
     *
     * @mbg.generated
     */
    public String getProfile() {
        return profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.profile
     *
     * @param profile the value for cms.account.profile
     *
     * @mbg.generated
     */
    public void setProfile(String profile) {
        this.profile = profile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.status
     *
     * @return the value of cms.account.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.status
     *
     * @param status the value for cms.account.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms.account.url
     *
     * @return the value of cms.account.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms.account.url
     *
     * @param url the value for cms.account.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }
}